// Generated by CoffeeScript 1.6.3
(function() {
  var CoffeeCup, a, c;

  CoffeeCup = (function() {
    function CoffeeCup() {}

    CoffeeCup.prototype.properties = {
      strength: 'medium',
      cream: false,
      sugar: false
    };

    CoffeeCup.prototype.strength = function(newS) {
      this.properties.strength = newS;
      return this;
    };

    CoffeeCup.prototype.cream = function(newC) {
      this.properties.cream = newC;
      return this;
    };

    CoffeeCup.prototype.sugar = function(newSu) {
      this.properties.sugar = newSu;
      return this;
    };

    return CoffeeCup;

  })();

  a = new CoffeeCup();

  console.log(JSON.stringify(a.properties));

  c = new CoffeeCup().strength('a').cream('b').sugar('c');

  console.log(JSON.stringify(c.properties));

  ("foo bar baz".split(' ').map(function(word) {
    return word[0].toUpperCase() + word.slice(1).toLowerCase();
  })).join(' ');

}).call(this);
